[project]
name = "e-book-v2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "flask>=3.1.2",
    "flask-cors>=6.0.2",
    "gtts>=2.5.4",
    "pytest>=9.0.2",
]
